export const Images = {
    loginbg: require("../../assets/Images/loginBg.png"),
    animatedLeft: require("../../assets/Images/vector1.png"),
    animatedRight: require("../../assets/Images/vector2.png"),
    astrologer1: require("../../assets/Images/astrologer1.jpg"),
    astrologer2: require("../../assets/Images/astrologer2.jpg"),
    astrologer3: require("../../assets/Images/astrologer3.jpg"),
    astrologer4: require("../../assets/Images/astrologer4.jpg"),
    astrologer5: require("../../assets/Images/astrologer1.jpg"),
    dailyhoro: require("../../assets/Images/dailyhoroscope.png"),
    freeKundli: require("../../assets/Images/freekundli1.png"),
    slotbg: require("../../assets/Images/slotbg.png"),
    userimg: require("../../assets/Images/userimg.png"),
    bookpooja: require("../../assets/Images/pooja.png"),
    orderhistory: require("../../assets/Images/orderhistory.png"),
    payment: require("../../assets/Images/onlinepayment.png"),
    home: require("../../assets/Images/home.png"),
    sidemenubg: require("../../assets/Images/sidemenubg.png"),
    astroconul: require("../../assets/Images/astrologyconsul.jpg"),
    AppRegistry: require("../../assets/Images/astrologyconsul.jpg"),
    aquarius: require("../../assets/Images/zodiac/aqarius.webp"),
    aries: require("../../assets/Images/zodiac/aries.webp"),
    cancer: require("../../assets/Images/zodiac/cancer.webp"),
    capricorn: require("../../assets/Images/zodiac/capricorn.webp"),
    gemini: require("../../assets/Images/zodiac/gemini.webp"),
    leo: require("../../assets/Images/zodiac/leo.webp"),
    libra: require("../../assets/Images/zodiac/libra.webp"),
    pisces: require("../../assets/Images/zodiac/pisces.webp"),
    saggitaurus: require("../../assets/Images/zodiac/saggitaurus.webp"),
    taurus: require("../../assets/Images/zodiac/taurus.webp"),
    virgo: require("../../assets/Images/zodiac/virgo.webp"),
    couple: require("../../assets/Images/Couple.png"),
    careerRemedy: require("../../assets/Images/career2.jpg"),
    educatRemedy: require("../../assets/Images/education.jpg"),
    health1Remedy: require("../../assets/Images/health1.jpg"),
    health2Remedy: require("../../assets/Images/health2.jpg"),
    marriage1Remedy: require("../../assets/Images/marriage.jpg"),
    marriageRemedy: require("../../assets/Images/marriage1.jpg"),
    famRemedy: require("../../assets/Images/fam1.jpg"),
    moneyRemedy: require("../../assets/Images/money.jpg"),
    tantraBooks: require("../../assets/Images/tantrabk.jpg"),
    onlineclasses: require("../../assets/Images/onlinecls.jpg"),
    onlineclasses: require("../../assets/Images/onlinecls.jpg"),
    bracelet1: require("../../assets/Images/bracelet1.jpg"),
    bracelet2: require("../../assets/Images/bracelet2.jpg"),
    capsules: require("../../assets/Images/capsules.jpg"),
    chain: require("../../assets/Images/chain.png"),
    oil: require("../../assets/Images/oil.jpg"),
    pendant: require("../../assets/Images/pendant.jpg"),
    kundalimatching: require("../../assets/Images/kundalimatching.png"),
    chaticon: require("../../assets/Images/chaticon.png"),
    poojaImg: require("../../assets/Images/poojas.jpg"),
    yagnaImg: require("../../assets/Images/yagnas.jpg"),
    panjapatchiImg: require("../../assets/Images/panjapatchi.png"),
    boxImg: require("../../assets/Images/box.png"),
    readyImg: require("../../assets/Images/ready.png"),
    num0: require("../../assets/Images/numbers/0.png"),
    num1: require("../../assets/Images/numbers/1.png"),
    num2: require("../../assets/Images/numbers/2.png"),
    num3: require("../../assets/Images/numbers/3.png"),
    num4: require("../../assets/Images/numbers/4.png"),
    num5: require("../../assets/Images/numbers/5.png"),
    num6: require("../../assets/Images/numbers/6.png"),
    num7: require("../../assets/Images/numbers/7.png"),
    num8: require("../../assets/Images/numbers/8.png"),
    num9: require("../../assets/Images/numbers/9.png"),
    aaplha: require("../../assets/Images/alphabets/a.png"),
    baplha: require("../../assets/Images/alphabets/b.png"),
    caplha:require("../../assets/Images/alphabets/c.png"),
    daplha:require("../../assets/Images/alphabets/d.png"),
    eaplha:require("../../assets/Images/alphabets/e.png"),
    faplha:require("../../assets/Images/alphabets/f.png"),
    gaplha:require("../../assets/Images/alphabets/g.png"),
    haplha:require("../../assets/Images/alphabets/h.png"),
    iaplha:require("../../assets/Images/alphabets/i.png"),
    japlha:require("../../assets/Images/alphabets/j.png"),
    kaplha:require("../../assets/Images/alphabets/k.png"),
    laplha:require("../../assets/Images/alphabets/l.png"),
    maplha:require("../../assets/Images/alphabets/m.png"),
    naplha:require("../../assets/Images/alphabets/n.png"),
    oaplha:require("../../assets/Images/alphabets/o.png"),
    paplha:require("../../assets/Images/alphabets/p.png"),
    qaplha:require("../../assets/Images/alphabets/q.png"),
    raplha:require("../../assets/Images/alphabets/r.png"),
    // saplha:require("../../assets/Images/alphabets/s.png"),
    taplha:require("../../assets/Images/alphabets/t.png"),
    uaplha:require("../../assets/Images/alphabets/u.png"),
    vaplha:require("../../assets/Images/alphabets/v.png"),
    waplha:require("../../assets/Images/alphabets/w.png"),
    xaplha:require("../../assets/Images/alphabets/x.png"),
    yaplha:require("../../assets/Images/alphabets/y.png"),
    zaplha:require("../../assets/Images/alphabets/z.png"),
    avatarfemale:require("../../assets/Images/avatarFemale.jpeg"),
    avatarmale:require("../../assets/Images/avatarMale.jpeg"),


};
