export const Images = {
    loginbg: require("../../assets/Images/loginBg.png"),
    animatedLeft:require("../../assets/Images/vector1.png"),
    animatedRight:require("../../assets/Images/vector2.png"),
    astrologer1:require("../../assets/Images/astrologer1.jpg"),
    astrologer2:require("../../assets/Images/astrologer2.jpg"),
    astrologer3:require("../../assets/Images/astrologer3.jpg"),
    astrologer4:require("../../assets/Images/astrologer4.jpg"),
    astrologer5:require("../../assets/Images/astrologer1.jpg"),
    dailyhoro:require("../../assets/Images/dailyhoroscope.png"),
    freeKundli:require("../../assets/Images/freekundli1.png"),
    slotbg:require("../../assets/Images/slotbg.png"),
    userimg:require("../../assets/Images/userimg.png"),
    bookpooja:require("../../assets/Images/pooja.png"),
    orderhistory:require("../../assets/Images/orderhistory.png"),
    payment:require("../../assets/Images/onlinepayment.png"),
    home:require("../../assets/Images/home.png"),
    sidemenubg:require("../../assets/Images/sidemenubg.png"),
    astroconul:require("../../assets/Images/astrologyconsul.jpg"),

};
